defaults:
  run:
    working-directory: "dev-deployment"

name: Spring Boot Deployment

on:
  workflow_dispatch:

env:
  image_tag: ${{ secrets.IMAGE_TAG }}
  environment: development
  project_id: off-net-dev
  repo_name: lendly-demo

jobs:
  Build:
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: "http://dev.test_demoApp.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: google-github-actions/auth@v1
        id: auth
        with:
          credentials_json: ${{ secrets.GCP_SA }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Deploy to Dev Enviroment
        run: |
          terraform apply -auto-approve \
            -var="environment=${{ env.environment }}" \
            -var="image_tag=${{ env.image_tag }}" \
            -var="project_id=${{ env.project_id }}" \
            -var="repo_name=${{ env.repo_name }}"
