defaults:
  run:
    working-directory: "terraform"

name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Checkout
        uses: actions/checkout@v3

      - uses: google-github-actions/auth@v1
        id: auth
        with:
          credentials_json: ${{ secrets.GCP_SA }}

      - name: Set TARGET_BRANCH environment variable
        run: echo "TARGET_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV

      - name: Echo target branch
        run: echo "The target branch is ${{ env.TARGET_BRANCH }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Set up JDK 17 for main branch
        if: env.TARGET_BRANCH == 'main'
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build JAR
        if: ${{ env.TARGET_BRANCH == 'main' }}
        run: mvn clean package -DskipTests
        working-directory: ./

      - name: Build & Push Docker Image (Only for Main Branch)
        if: env.TARGET_BRANCH == 'main'
        run: |
          gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev
          docker build -t northamerica-northeast1-docker.pkg.dev/off-net-dev/lendly-demo/spring-boot-rest-app:latest .
          docker push northamerica-northeast1-docker.pkg.dev/off-net-dev/lendly-demo/spring-boot-rest-app:latest
        working-directory: ./

      - name: Terraform Apply (Main)
        if: env.TARGET_BRANCH == 'main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      - name: Terraform Apply (Staging)
        if: env.TARGET_BRANCH == 'staging' && github.event_name == 'push'
        run: terraform apply -auto-approve -var="image_tag=latest"
